import './js/components/header';
import './js/components/hero';
import './js/components/weekly';
import './js/components/upcoming';
import './js/components/modal';
import './js/components/footer';
import './js/utils/scroll-up';
import './js/utils/loader';
import './js/utils/thams';
